### PR TITLE
Adding REPL support

### PR DESCRIPTION
**Pull request by tninja**
credit to https://github.com/sarvex/kotlin-mode

### CODE REVIEW

**Comment by tninja** [comment]
Tested on my locale machine.

**Comment by gregghz** [comment]
This looks great. I haven't tested it yet but I will and assuming it all works I'll merge.

**Comment by ilanpillemer** [comment]
Any reason why this is not merged in yet? Or do I have to pull from a different project to get this?

**Review by gregghz — APPROVED** [review]

**Comment by gregghz** [comment]
@ilanpillemer just merged it, sorry for the delay :)

**Pull request merged**
