### PR TITLE
More emacs-like indentation.

### PR DESCRIPTION
**Pull request by jcpetkovich**
This places the cursor at the end of the whitespace of the indentation if the cursor starts somewhere within the whitespace. Otherwise it tries to preserve the position of the cursor via `save-excursion`, this is what e.g., `c-mode`, `python-mode`, `java-mode`, and many others do by default.

### CODE REVIEW

**Comment by russel** [comment]
This looks good to me on inspection, but I haven't been able to try it out for real.

**Comment by gregghz** [comment]
@jcpetkovich there's some merge conflicts in this. I made the mistake of merging a newer PR before this one, I should have gone with oldest first, sorry about that.

**Comment by bwo** [comment]
the present indentation behavior is incredibly annoying

**Comment by pyloolex** [comment]
> the present indentation behavior is incredibly annoying

@bwo it's not just annoying. It's outrageous and disgusting. No wonder there are 4 open PRs - all related to the indentation.

@gregghz , @russel could you please review open pull requests? It would be extremely helpful if the indentation fixes were merged.

**Comment by pyloolex** [comment]
@jcpetkovich could you please resolve merge conflicts?

**Comment by jcpetkovich** [comment]
@pyloolex fixed! Sorry for the delay, busy with the holiday rush.

**Pull request merged**
